### ISSUE TITLE
Suggestion: How to get the solution for parsing JSON to work in stable

### ISSUE THREAD

**Issue by booyaa** [Mercateo/rust-for-node-developers#10]
The [serde.rs](https://serde.rs) website has had a revamp and the instructions for using a hybrid codegen solution are easier to [find](https://serde.rs/codegen-hybrid.html).

I'm happy to make the changes to the documentation and example code  if there's interest.

**Comment by donaldpipowitch** [comment]
I thought about this, too. (See [this question](https://users.rust-lang.org/t/how-to-correctly-map-a-vector-into-another/7208/1).) It seemed to me like codegen would add a lot of noise for little benefit. While using `derive` needs a nightly currently, it will be _the_ way to solve this problem in the future. At least as far as I know. So when `derive` becomes stable, there is no need for codegen anymore. Correct me if I'm wrong with this.

And as far as I know `derive` isn't that far away from becoming stable.

I don't know if it worth the effort to have a really plain solution without codegen, though.  That was my first attempt. Using `serde_json`s `Value` and matching the right types... But at the end I thought that would be also too much noise and that `derive` - while requiring nightly - will be the more future-proof way of doing this.

**Comment by donaldpipowitch** [comment]
Added an example in the rewrite.
