### ISSUE TITLE
Introduce raw string literals?

### ISSUE THREAD

**Issue by killercup** [Mercateo/rust-for-node-developers#2]
You have several examples like

```rust
println!("Required \"{}\".", HELLO_WORLD);
```

that look pretty ugly. It'd write them like this

```rust
println!(r#"Required "{}"."#, HELLO_WORLD);
```

You can find more about this syntax [in this part of the reference](https://doc.rust-lang.org/reference.html#raw-string-literals).

**Comment by donaldpipowitch** [comment]
Thanks. Are there any advantages besides that you don't have to escape `"`? I probably would just rewrite the example to something like `println!("Required: {}.", HELLO_WORLD);` than so I don't introduce too much at once :)

**Comment by killercup** [comment]
I think the `r` specifier allows some additional escaping stuff, so you don't need to escape `\` in a regex for example.

I thought you explicitly used `"Required \"{}\"."` to show how escaping works :)

**Comment by donaldpipowitch** [comment]
> I thought you explicitly used "Required \"{}\"." to show how escaping works :)

It happened accidentally :)
