### ISSUE TITLE
Suggestion: write as Gitbook

### ISSUE THREAD

**Issue by leesei** [Mercateo/rust-for-node-developers#5]
First of all thanks for the effort.

Have you considered using [Gitbook](https://www.npmjs.com/package/gitbook/) for publishing?
It also helps you export to various formats.
That's better than reading on Github.

**Comment by leesei** [comment]
Forgot to mention, if you agree with that, I can help and try Gitbook on the current repo.

**Comment by donaldpipowitch** [comment]
Actually I thought about it, but didn't know if it would be overkill. I'm not sure if I need the features of Gitbook or if it makes contributing harder. It would be nice to know what other people think.

**Comment by leesei** [comment]
IMO the MD themselves are more or less the same if we ported to Gitbook, we have the option to link to other MDs with Gitbook's syntax.
Then we add a couple of top level file for Gitbook.

**Comment by donaldpipowitch** [comment]
Well, give it a shot. If you can write me a small explanation of what you did that would be great :)

**Comment by piranna** [comment]
I've written my [bachelor thesis](https://github.com/piranna/pfc) in GitBook and although it still has some flaws for scientific material, it's an awesome tool to write documentation: if you know markdown, you can write a GitBook :-)

**Comment by donaldpipowitch** [comment]
I currently rewrite the articles, but I keep the current format for now.
