### ISSUE TITLE
Example of Node.js compiled module

### ISSUE THREAD

**Issue by piranna** [Mercateo/rust-for-node-developers#9]
Node.js compiled modules are usually written in C++, but being this a tutorial of Rust for Node.js developers, maybe it would be a cool lesson how to write a simple Node.js compiled module that print a hello world message in Rust and require it from Node.js :-)

**Comment by donaldpipowitch** [comment]
Yeah, that is a fantastic goal and I definitely want to try this! I already read about the neon project which tries to make this easy. As I do not know C++ I couldn't write a native add-on before. But I guess I'll do three to four more examples before I do that (probably about making HTTP requests, setting up a server and things like that).

**Comment by donaldpipowitch** [comment]
I currently rewrite the articles and hope to maybe add a chapter about wasm which would also allow to use some Rust code in a Node project.
